version: "3"
services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - geolocation-server
  web-api:
    build: .
    container_name: "web-api"
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - geolocation-server
  redis:
    image: redis:7.2-alpine
    container_name: "redis"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - geolocation-server
volumes:
  redisdata:
    driver: local
networks:
  geolocation-server:
    driver: bridge