version: "3"
services: 
  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"  # Exponha a porta 80 do Nginx para tráfego externo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Monte o arquivo de configuração do Nginx
    depends_on:
      - web-api  # Nginx depende do web-api estar em execução
    networks:
      - geolocation-api
  web-api:
    build: .
    container_name: "web-api"
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - geolocation-api
  redis:
    image: redis:7.2-alpine
    container_name: "redis"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - geolocation-api
volumes:
  redisdata:
    driver: local
networks:
  geolocation-api:
    driver: bridge